### PR TITLE
Improve/docs

### PR DESCRIPTION
**Pull request by dominikh**

### CODE REVIEW

**Comment by basicxman** [comment]
`Extensions#parse_commands` uses the @note tag to define key/value pairs for commands.  Check out https://github.com/basicxman/minecraft/blob/development/lib/minecraft/extensions.rb#L81

I don't think it's needed to to note that each command returns void.

**Comment by dominikh** [comment]
> I don't think it's needed to to note that each command returns void

Well, it greatly improves the generated documentation, because instead of a ton of methods that return `Object` you now have a clear indicator that they have no meaningful return value. And combined with --hide-void-return, those return values will be completely hidden.

**Comment by dominikh** [comment]
Regarding the parsing of the @note tag: You could tap directly into the YARD API and read the @level tags, instead of manually parsing the docstring.

**Comment by basicxman** [comment]
Yes however there is currently another @note use, the message for when an all command is executed.  There is likely to be future note tags as well.

I'm merging your grammar and return commits.

**Comment by dominikh** [comment]
Ultimatively the right way would be to have separate tags for your @note usages, i.e. use the documentation as a proper key/value store. Manually parsing the docstring is prone to errors, at the latest when you start using @overload.

**Pull request closed without merging**
